save_data: /content/VRepair2.0/param_sweep_tgt/00_parameter_sweep_codebertcpp/data
src_vocab: /content/VRepair2.0/param_sweep_tgt/00_parameter_sweep_codebertcpp/data.vocab.src
tgt_vocab: /content/VRepair2.0/param_sweep_tgt/00_parameter_sweep_codebertcpp/data.vocab.tgt
overwrite: false
n_sample: -1
data:
  github:
    path_src: /content/VRepair2.0/vul_data/random_fine_tune_train.src.txt
    path_tgt: /content/VRepair2.0/vul_data/random_fine_tune_train.tgt.txt
  valid:
    path_src: /content/VRepair2.0/vul_data/random_fine_tune_valid.src.txt
    path_tgt: /content/VRepair2.0/vul_data/random_fine_tune_valid.tgt.txt
seed: 0
